import type { BOQ } from "@/types/boq";
import { buildDocumentData, type BuildDocumentDataInput, type CanonicalDocumentData, type DocumentAudienceValue } from "./build-document-data";

const SAMPLE_BOQ: BOQ = {
  id: "sample-boq",
  projectId: "sample-project",
  title: "Sample BOQ",
  revision: "R01",
  status: "locked",
  taxRate: 5,
  isLocked: true,
  createdAt: new Date().toISOString(),
  lockedAt: new Date().toISOString(),
  sections: [
    {
      id: "sample-section",
      code: "GEN",
      title: "General Works",
      description: "",
      order: 1,
      items: [
        {
          id: "sample-item-1",
          itemNumber: 1,
          itemCode: "SAMPLE-001",
          category: "Sample",
          description: "Sample line item description for template preview",
          specification: "Reference specification text",
          quantity: 10,
          unit: "nr",
          unitCost: 100,
          freightCost: 5,
          installationCost: 0,
          additionalCost: 0,
          landedCost: 105,
          marginMode: "markup",
          marginPercentage: 20,
          sellingRate: 126,
          totalAmount: 1260,
          wastagePercentage: 0,
          taxApplicable: true,
          sourceReference: "",
          roomOrZone: "Zone A",
          drawingReference: "A-100",
          confidenceScore: 100,
          status: "confirmed",
          notes: "",
          options: [],
        },
        {
          id: "sample-item-2",
          itemNumber: 2,
          itemCode: "SAMPLE-002",
          category: "Sample",
          description: "Second sample line item for template preview",
          specification: "Reference specification text",
          quantity: 5,
          unit: "m2",
          unitCost: 250,
          freightCost: 0,
          installationCost: 20,
          additionalCost: 0,
          landedCost: 270,
          marginMode: "markup",
          marginPercentage: 18,
          sellingRate: 318.6,
          totalAmount: 1593,
          wastagePercentage: 0,
          taxApplicable: true,
          sourceReference: "",
          roomOrZone: "Zone B",
          drawingReference: "A-101",
          confidenceScore: 100,
          status: "confirmed",
          notes: "",
          options: [],
        },
      ],
    },
  ],
  totals: {
    directCost: 1875,
    landedCost: 1875,
    grossProfit: 978,
    grossMarginPercentage: 34.3,
    subtotal: 2853,
    discountPercentage: 0,
    discountAmount: 0,
    taxableAmount: 2853,
    taxAmount: 142.65,
    grandTotal: 2995.65,
  },
};

/** A hardcoded, self-contained fixture used only for the "Preview" action in template management, where no real project/BOQ has been selected yet. */
export function buildSampleDocumentData(
  overrides: Pick<BuildDocumentDataInput, "templateName" | "documentType"> & {
    audience?: DocumentAudienceValue;
    showInternalCostFieldsToClient?: boolean;
  },
): CanonicalDocumentData {
  return buildDocumentData({
    company: {
      legalName: "Sample Contracting LLC",
      tradeName: "Sample Co",
      email: "info@example.com",
      phone: "+971-4-000-0000",
      website: "example.com",
      address: "Business Bay, Dubai, UAE",
      taxRegistrationNumber: "100000000000003",
      defaultCurrency: "AED",
    },
    client: {
      name: "Sample Client LLC",
      companyName: "Sample Client LLC",
      email: "client@example.com",
      phone: "+971-4-000-1111",
      address: "Downtown Dubai, UAE",
      taxRegistrationNumber: null,
    },
    project: {
      name: "Sample Project",
      reference: "SAMPLE-001",
      location: "Dubai, UAE",
      currency: "AED",
      taxRate: 5,
      language: "English",
    },
    industryName: "Sample Industry",
    boq: SAMPLE_BOQ,
    revisionNumber: 1,
    audience: overrides.audience ?? "CLIENT",
    templateName: overrides.templateName,
    documentType: overrides.documentType,
    generatedByName: "Preview",
    isDraft: false,
    showInternalCostFieldsToClient: overrides.showInternalCostFieldsToClient,
  });
}
