import type { IndustryEngine } from "@/types/industry";

export const constructionEngine: IndustryEngine = {
  id: "construction",
  name: "Construction",
  shortName: "Construction",
  description: "Structural and civil BOQ workflows for building construction projects.",
  icon: "hammer",
  status: "active",
  supportedUnits: ["m3", "m2", "lm", "tonne", "kg", "nos", "LS"],
  boqSections: [
    { id: "preliminaries", code: "PRE", title: "Preliminaries", description: "Site setup and general conditions.", order: 1 },
    { id: "foundations", code: "FND", title: "Foundations", description: "Concrete and reinforcement works.", order: 2 },
    { id: "concrete", code: "CON", title: "Concrete Works", description: "Concrete batching and placement.", order: 3 },
    { id: "formwork", code: "FRM", title: "Formwork", description: "Formwork installation and removal.", order: 4 },
    { id: "blockwork", code: "BLK", title: "Blockwork", description: "Wall construction with block units.", order: 5 },
    { id: "waterproofing", code: "WPF", title: "Waterproofing", description: "Protective waterproof membrane works.", order: 6 },
    { id: "area-schedules", code: "ARE", title: "Measured Areas", description: "Explicitly stated and reconciled gross and net areas.", order: 7 },
    { id: "space-schedules", code: "SPC", title: "Room and Space Schedules", description: "Reconciled scheduled rooms and spaces.", order: 8 },
    { id: "floor-finishes", code: "FLR", title: "Floor Finishes", description: "Floor finishes measured from coordinated plans and schedules.", order: 9 },
    { id: "ceilings", code: "CLG", title: "Ceilings", description: "Ceilings measured from coordinated reflected ceiling plans.", order: 10 },
    { id: "wall-finishes", code: "WFL", title: "Wall Finishes", description: "Wall finishes measured from coordinated elevations and schedules.", order: 11 },
    { id: "openings", code: "OPN", title: "Doors and Windows", description: "Openings reconciled against plans and schedules.", order: 12 },
    { id: "partitions", code: "PAR", title: "Partitions", description: "Partitions measured from coordinated layouts and details.", order: 13 },
    { id: "external-works", code: "EXT", title: "External Works", description: "External works measured from coordinated plans and schedules.", order: 14 },
  ],
  requiredFields: ["concreteGrade", "reinforcementDiameter", "reinforcementWeight", "formworkArea", "elementType", "floorLevel", "structuralReference"],
  calculationTypes: ["concreteVolume", "reinforcementTotal", "formworkArea", "excavationVolume", "wallArea", "grossFloorArea", "netFloorArea", "roomCount", "flooringArea", "ceilingArea", "wallFinishArea", "openingCount", "partitionArea", "externalWorksArea"],
  validationRules: ["quantityPositive", "unitRequired", "codeUnique", "marginWithinRange"],
  documentLabels: { boq: "Construction BOQ", revision: "Revision", total: "Total Contract Value" },
  dashboardMetrics: [
    { label: "Structural BOQs", value: "12", status: "normal" },
    { label: "Approved Sections", value: "8", status: "success" },
  ],
};
