import type { IndustryEngine } from "@/types/industry";

export const FURNITURE_SCHEDULE_FIELDS = [
  "item",
  "specification",
  "room",
  "location",
  "quantity",
  "unit",
  "width",
  "height",
  "depth",
  "material",
  "finishColour",
  "manufacturer",
  "productReference",
  "installation",
  "hardwareAccessories",
  "manufacturingComponents",
  "sourceReference",
  "pageNumber",
  "evidence",
  "confidence",
  "verificationStatus",
  "notes",
  "assumptions",
] as const;

export const furnitureEngine: IndustryEngine = {
  id: "furniture",
  name: "Furniture",
  shortName: "Furniture",
  description: "Loose and manufactured furniture schedules with product references, dimensions when available, finishes, installation, evidence, and professional verification.",
  icon: "chair",
  status: "active",
  supportedUnits: ["pcs", "sets", "units", "LS"],
  boqSections: [
    { id: "executive-furniture", code: "EXE", title: "Executive Furniture", description: "Office executive furniture items.", order: 1 },
    { id: "workstations", code: "WRK", title: "Workstations", description: "Modular workstation systems.", order: 2 },
    { id: "seating", code: "SEA", title: "Seating", description: "Chairs and lounge seating.", order: 3 },
    { id: "storage", code: "STO", title: "Storage", description: "Cabinets and storage furniture.", order: 4 },
  ],
  requiredFields: [...FURNITURE_SCHEDULE_FIELDS],
  calculationTypes: ["unitCount", "setQuantity", "optionSelection"],
  validationRules: ["quantityPositive", "specificationRequired", "optionSelectionValid"],
  documentLabels: { boq: "Furniture BOQ", itemsList: "Furniture Package" },
  dashboardMetrics: [
    { label: "Furniture Lines", value: "28", status: "normal" },
    { label: "Option Sets", value: "9", status: "success" },
  ],
};
