import { Metadata } from "next";
import KnowledgePage, { KnowledgePageContent } from "@/components/layout/knowledge-page";

export const metadata: Metadata = {
  title: "BOQ Review Checklist for Contractors and Estimators | Quantara",
  description: "Use this practical BOQ review checklist to examine scope, quantities, units, descriptions, revisions, assumptions, exclusions and document consistency.",
  alternates: {
    canonical: "https://quantara.vistabylara.com/boq-review-checklist",
  },
  openGraph: {
    title: "BOQ Review Checklist for Contractors and Estimators | Quantara",
    description: "Use this practical BOQ review checklist to examine scope, quantities, units, descriptions, revisions, assumptions, exclusions and document consistency.",
    url: "https://quantara.vistabylara.com/boq-review-checklist",
    type: "article",
  },
};

export default function Page() {
  const content: KnowledgePageContent = {
    breadcrumbLabel: "BOQ Review Checklist Before Tender, Pricing or Issue",
    title: "BOQ Review Checklist Before Tender, Pricing or Issue",
    summary: "A thorough review of a Bill of Quantities (BOQ) is a critical quality control step before submitting a tender, issuing a document to subcontractors, or signing a contract. This practical checklist helps estimators and commercial teams systematically identify errors, omissions, and commercial risks within the BOQ structure.",
    reviewedDate: new Date().toISOString().split("T")[0],
    sections: [
  {
    "id": "why-it-matters",
    "heading": "Why a Formal Review Matters",
    "paragraphs": [
      "For contractors, commercial managers, and estimators, discovering a major error in a BOQ after the contract is signed can destroy a project's profit margin.",
      "Whether you are reviewing a BOQ issued by a client, or checking an internal BOQ generated by your own team, a structured review process ensures that all assumptions are documented and quantities align with reality."
    ]
  },
  {
    "id": "the-checklist",
    "heading": "Comprehensive Review Checklist",
    "checklists": [
      {
        "groupTitle": "Document and Version Control",
        "items": [
          "Confirm the BOQ references the correct project name and client details.",
          "Verify the BOQ revision number matches the latest issued addenda.",
          "Check that all referenced drawing numbers and specification dates match the current set.",
          "Ensure a formal revision history is present and changes are tracked."
        ]
      },
      {
        "groupTitle": "Scope and Descriptions",
        "items": [
          "Check for missing scope (items on drawings but not in the BOQ).",
          "Check for duplicated scope (items appearing in multiple sections or trades).",
          "Ensure item descriptions are unambiguous and reference the correct specification clauses.",
          "Verify that assumptions regarding ambiguous scope are explicitly documented.",
          "Confirm that exclusions (e.g., client-supplied items) are clearly stated."
        ]
      },
      {
        "groupTitle": "Quantities and Measurement",
        "items": [
          "Spot-check major quantities against high-level drawing measurements.",
          "Verify that appropriate units of measurement are used (e.g., m2 for areas, m3 for volumes).",
          "Check for obvious transcription or decimal placement errors in quantities.",
          "Ensure provisional quantities are clearly marked as subject to remeasurement."
        ]
      },
      {
        "groupTitle": "Pricing and Formatting (if applicable)",
        "items": [
          "Verify that all rates have been entered and no items have been left blank accidentally.",
          "Check that section totals sum correctly to the summary page.",
          "Ensure formatting, page breaks, and table structures are intact.",
          "Obtain final professional approval and signature from a qualified senior reviewer."
        ]
      }
    ]
  },
  {
    "id": "practical-example",
    "heading": "A Practical Example",
    "paragraphs": [
      "During a review of a hypothetical plumbing BOQ, an estimator uses this checklist and notices an item for \"150mm copper pipe\" has a unit of \"m2\" instead of linear meters (\"m\").",
      "This simple unit error, caught by the checklist, prevents a massive miscalculation in the final tender price."
    ]
  },
  {
    "id": "limitations",
    "heading": "Limitations of a Checklist",
    "paragraphs": [
      "No checklist can replace professional experience. A checklist ensures you don't forget to check the drawings, but it cannot tell you if the architectural design is fundamentally flawed.",
      "Always require a qualified construction professional to interpret the technical nuances of the scope."
    ]
  },
  {
    "id": "quantara-workflow",
    "heading": "How Quantara Supports BOQ Review",
    "paragraphs": [
      "When reviewing PDFs, data can easily be misread. Quantara extracts PDF BOQs into structured data, allowing teams to run checks on formulas, units, and missing items much faster than scanning pages manually.",
      "Quantara currently focuses on supported document extraction, BOQ structuring, project organization, templates, revisions, and professional outputs."
    ]
  }
],
    faqs: [
  {
    "question": "Who should review the BOQ?",
    "answer": "A BOQ should be reviewed by a senior estimator, commercial manager, or qualified quantity surveyor who was ideally not the person who initially prepared it."
  },
  {
    "question": "When should the review take place?",
    "answer": "A review should occur before a consultant issues the BOQ for tender, and again by the contractor before submitting their priced bid."
  },
  {
    "question": "What is a provisional sum check?",
    "answer": "Reviewing provisional sums ensures that allowances for unknown work are correctly segregated and do not accidentally include scope that is already measured elsewhere."
  },
  {
    "question": "How do you check formulas in a PDF BOQ?",
    "answer": "In a PDF, formulas cannot be clicked. They must be manually recalculated, or the data must be extracted into a digital format like Excel or Quantara to verify the math."
  },
  {
    "question": "Why check specification references?",
    "answer": "An item might say \"Standard door,\" but the specification reference might mandate a highly expensive fire-rated acoustic door. Checking the reference prevents underpricing."
  }
],
    relatedReading: [
  {
    "href": "/common-boq-errors",
    "label": "Common BOQ Errors"
  },
  {
    "href": "/how-to-review-ai-extracted-boq",
    "label": "Reviewing AI-Extracted BOQs"
  },
  {
    "href": "/boq-revision-control",
    "label": "BOQ Revision Control"
  }
],
    schema: {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      "headline": "BOQ Review Checklist Before Tender, Pricing or Issue",
      "description": "Use this practical BOQ review checklist to examine scope, quantities, units, descriptions, revisions, assumptions, exclusions and document consistency.",
      "url": "https://quantara.vistabylara.com/boq-review-checklist",
      "publisher": { "@id": "https://quantara.vistabylara.com/#organization" },
      "mainEntityOfPage": { "@id": "https://quantara.vistabylara.com/#website" }
    }
  };

  return <KnowledgePage content={content} />;
}
