import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    '',
    '/features',
    '/about',
    '/security',
    '/terms',
    '/privacy',
    '/data-processing',
    '/cookie-policy',
    '/acceptable-use',
    '/subprocessors',
    '/contact-sales',
    '/login',
    '/register',
    '/ai-boq-software',
    '/boq-software',
    '/construction-estimating-software',
    '/boq-management',
    '/pdf-boq-extraction',
    '/scanned-pdf-boq',
    '/quantity-surveying-software',
    '/boq-document-generation',
    '/resources',
    '/what-is-a-boq',
    '/boq-vs-construction-estimate',
    '/boq-vs-bill-of-materials',
    '/how-to-prepare-a-boq',
    '/boq-review-checklist',
    '/common-boq-errors',
    '/boq-revision-control',
    '/how-to-convert-pdf-boq-to-excel',
    '/text-pdf-vs-scanned-pdf',
    '/ocr-for-boq-documents',
    '/how-to-review-ai-extracted-boq',
    "/quantity-takeoff-vs-boq-management",
    "/industries",
    "/boq-software-for-contractors",
    "/boq-software-for-quantity-surveyors",
    "/boq-software-for-mep-contractors",
    "/boq-software-for-hvac-contractors",
    "/boq-software-for-fit-out-companies",
    "/boq-software-for-fire-fighting-contractors",
    "/boq-software-for-facilities-management",
    "/boq-software-for-engineering-consultants",
    "/gcc-boq-software",
    "/boq-software-uae",
    "/boq-software-dubai",
    "/boq-software-abu-dhabi",
    "/construction-estimating-software-uae",
    "/mep-estimating-software-uae",
    "/boq-software-saudi-arabia",
    "/boq-software-qatar",
    "/boq-software-oman",
    "/comparisons",
    "/quantara-vs-excel-for-boq",
    "/boq-software-vs-spreadsheets",
    "/ai-boq-vs-manual-boq-preparation",
    "/ocr-vs-structured-boq-extraction",
    "/quantity-takeoff-vs-boq-software",
    "/boq-software-vs-document-management",
    "/construction-estimating-software-vs-excel",
    "/when-to-use-boq-software",
    "/site-map"
  ];

  return routes.map((route) => ({
    url: `https://quantara.vistabylara.com${route}`,
    lastModified: new Date('2026-08-05'),
    changeFrequency: route === '' ? 'weekly' : 'monthly',
    priority: route === '' ? 1 : 0.8,
  }));
}
