import type { ProviderRegistryEntry } from "./connector-types";

/**
 * INTEGRATIONS-1A — the single source of truth for every provider shown in
 * the marketplace. Purely static/code-driven so the marketplace renders
 * without any database dependency (lesson from MASTER-BOQ-1A: never make a
 * primary page's render depend on a migration that may not have run yet).
 * `IntegrationProvider` DB rows are seeded from this file for 1B+ to
 * reference by a stable id, but the UI reads this array directly.
 *
 * Status honesty rule for this phase: no connector has shipped yet in
 * INTEGRATIONS-1A (not even Autodesk OAuth — explicitly deferred to 1B and
 * beyond, separately approved). Every OAuth-cloud provider is therefore
 * COMING_SOON right now regardless of its eventual target status, and every
 * plugin/file-import-ceiling provider shows the status that honestly
 * describes how it will *ever* connect (REQUIRES_PLUGIN / FILE_IMPORT_ONLY),
 * since that is true independent of Quantara's build progress. No provider
 * in this file is AVAILABLE, BETA, or CONNECTED — none of those would be
 * true yet.
 */
export const PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  // ---------------------------------------------------------------- Autodesk
  {
    id: "autodesk",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Autodesk",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Connect your Autodesk account to browse hubs, projects, and models across the Autodesk ecosystem.",
    description: "Autodesk Platform Services OAuth, Data Management API, and Model Derivative API — one connection powers every Autodesk product below.",
    supportedData: [],
    plannedData: ["Hub/account access", "Project and folder browsing", "File/model version selection", "Metadata synchronization"],
    recommendedOrder: 1,
    icon: "Box",
    isIndependentIntegration: true,
  },
  {
    id: "revit",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Revit",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "BIM authoring and structured model data.",
    description: "Available through the Autodesk connection above, not a separate login — RVT files, model versions, and element metadata where enabled.",
    supportedData: [],
    plannedData: ["RVT files", "Model versions", "Element metadata where enabled"],
    recommendedOrder: 2,
    icon: "Building2",
    isIndependentIntegration: true,
  },
  {
    id: "autocad",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "AutoCAD",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "2D/3D CAD drawings.",
    description: "Available through the Autodesk connection — DWG files and drawing property extraction where enabled.",
    supportedData: [],
    plannedData: ["DWG files", "Drawing property extraction"],
    recommendedOrder: 3,
    icon: "PenTool",
    isIndependentIntegration: true,
  },
  {
    id: "autodesk-construction-cloud",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Autodesk Construction Cloud",
    category: "CONSTRUCTION_MANAGEMENT",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Construction project data, docs, and coordination.",
    description: "Available through the Autodesk connection — includes Autodesk Docs and BIM 360 projects.",
    supportedData: [],
    plannedData: ["Project documents", "Issues and RFIs", "Sheet sets"],
    recommendedOrder: 4,
    icon: "HardHat",
    isIndependentIntegration: true,
  },
  {
    id: "autodesk-docs",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Autodesk Docs",
    category: "COMMON_DATA_ENVIRONMENTS",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Common data environment for Autodesk project files.",
    description: "Available through the Autodesk connection.",
    supportedData: [],
    plannedData: ["Folder browsing", "Document versions"],
    recommendedOrder: null,
    icon: "FolderOpen",
    isIndependentIntegration: true,
  },
  {
    id: "bim-360",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "BIM 360",
    category: "COMMON_DATA_ENVIRONMENTS",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Legacy Autodesk construction cloud environment.",
    description: "Available through the Autodesk connection where still supported by the account.",
    supportedData: [],
    plannedData: ["Project documents", "Issues"],
    recommendedOrder: null,
    icon: "FolderOpen",
    isIndependentIntegration: true,
  },
  {
    id: "civil-3d",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Civil 3D",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Civil infrastructure design and object data.",
    description: "Available through the Autodesk connection — civil object data planned for a future phase.",
    supportedData: [],
    plannedData: ["Civil 3D object data"],
    recommendedOrder: 13,
    icon: "Route",
    isIndependentIntegration: true,
  },
  {
    id: "navisworks",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Navisworks",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Model coordination and clash detection.",
    description: "Available through the Autodesk connection — model coordination planned for a future phase.",
    supportedData: [],
    plannedData: ["Model coordination"],
    recommendedOrder: 12,
    icon: "GitMerge",
    isIndependentIntegration: true,
  },
  {
    id: "3ds-max",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "3ds Max",
    category: "VISUALIZATION_RENDERING",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Visualization and rendering.",
    description: "Available through the Autodesk connection — automation/rendering planned for a future phase.",
    supportedData: [],
    plannedData: ["Automation/rendering"],
    recommendedOrder: 16,
    icon: "Sparkles",
    isIndependentIntegration: true,
  },
  {
    id: "inventor",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Inventor",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Mechanical design and manufacturing.",
    description: "Available through the Autodesk connection.",
    supportedData: [],
    plannedData: ["Assembly/part data"],
    recommendedOrder: null,
    icon: "Wrench",
    isIndependentIntegration: true,
  },
  {
    id: "fusion",
    providerFamily: "autodesk",
    familyDisplayName: "Autodesk",
    displayName: "Fusion",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Cloud-based CAD/CAM/CAE.",
    description: "Available through the Autodesk connection.",
    supportedData: [],
    plannedData: ["Design data"],
    recommendedOrder: null,
    icon: "Cpu",
    isIndependentIntegration: true,
  },

  // ------------------------------------------------------------- Tier 1 rest
  {
    id: "trimble-connect",
    providerFamily: "trimble",
    familyDisplayName: "Trimble",
    displayName: "Trimble Connect",
    category: "COMMON_DATA_ENVIRONMENTS",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Trimble's common data environment for BIM collaboration.",
    description: "Trimble Identity OAuth with regional endpoint discovery — browse projects, folders, and BIM models.",
    supportedData: [],
    plannedData: ["Project/folder/file browsing", "BIM model linking", "Model metadata sync"],
    recommendedOrder: 7,
    icon: "Boxes",
    isIndependentIntegration: true,
  },
  {
    id: "procore",
    providerFamily: "procore",
    familyDisplayName: "Procore",
    displayName: "Procore",
    category: "CONSTRUCTION_MANAGEMENT",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Construction project management and cost codes.",
    description: "Procore OAuth with project-level permissions — browse projects, read drawings/documents and cost codes.",
    supportedData: [],
    plannedData: ["Project browsing", "Drawings/documents", "Cost codes", "Selected document import"],
    recommendedOrder: 6,
    icon: "ClipboardList",
    isIndependentIntegration: true,
  },
  {
    id: "bentley-itwin",
    providerFamily: "bentley",
    familyDisplayName: "Bentley Systems",
    displayName: "Bentley iTwin",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Digital twin and infrastructure model access.",
    description: "Bentley OAuth authorization-code flow — browse authorized iTwins and link project/model data.",
    supportedData: [],
    plannedData: ["iTwin browsing", "Project/model linking", "Metadata sync"],
    recommendedOrder: 9,
    icon: "Globe",
    isIndependentIntegration: true,
  },
  {
    id: "bluebeam-studio",
    providerFamily: "bluebeam",
    familyDisplayName: "Bluebeam",
    displayName: "Bluebeam Studio",
    category: "DOCUMENTS_STORAGE",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "PDF markup and review sessions.",
    description: "Bluebeam Studio OAuth — browse authorized Studio projects/sessions and import reviewed PDF drawings.",
    supportedData: [],
    plannedData: ["Studio project/session browsing", "PDF drawing import", "Source metadata"],
    recommendedOrder: 8,
    icon: "FileEdit",
    isIndependentIntegration: true,
  },

  // ---------------------------------------------------------- Tier 2 storage
  {
    id: "microsoft-365",
    providerFamily: "microsoft",
    familyDisplayName: "Microsoft",
    displayName: "Microsoft 365",
    category: "DOCUMENTS_STORAGE",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "OneDrive, SharePoint, and Teams files via one Microsoft Graph connection.",
    description: "One Microsoft Graph OAuth connector covers OneDrive, OneDrive for Business, SharePoint, and Microsoft Teams Files — no separate logins per product.",
    supportedData: [],
    plannedData: ["Drive/site/library browsing", "File picker", "Permitted file import/link", "Version metadata"],
    recommendedOrder: 10,
    icon: "Cloud",
    isIndependentIntegration: true,
  },
  {
    id: "google-drive",
    providerFamily: "google",
    familyDisplayName: "Google",
    displayName: "Google Drive",
    category: "DOCUMENTS_STORAGE",
    connectionType: "OAUTH_CLOUD",
    status: "AVAILABLE",
    shortPurpose: "Cloud file storage.",
    description: "Google OAuth with least-privilege (read-only) scope — browse folders and files directly from Drive.",
    supportedData: ["Folder/file browsing"],
    plannedData: ["Selected file import into a project", "Version metadata"],
    recommendedOrder: 11,
    icon: "HardDrive",
    isIndependentIntegration: true,
  },
  {
    id: "dropbox",
    providerFamily: "dropbox",
    familyDisplayName: "Dropbox",
    displayName: "Dropbox",
    category: "DOCUMENTS_STORAGE",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Cloud file storage.",
    description: "Dropbox OAuth — file/folder picker for supported files.",
    supportedData: [],
    plannedData: ["File/folder picker", "Supported file import", "Version metadata where available"],
    recommendedOrder: null,
    icon: "HardDrive",
    isIndependentIntegration: true,
  },
  {
    id: "box",
    providerFamily: "box",
    familyDisplayName: "Box",
    displayName: "Box",
    category: "DOCUMENTS_STORAGE",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Enterprise cloud content management.",
    description: "Box OAuth — enterprise file picker for folder/file import.",
    supportedData: [],
    plannedData: ["Enterprise file picker", "Folder/file import", "Version metadata"],
    recommendedOrder: null,
    icon: "Package",
    isIndependentIntegration: true,
  },

  // ------------------------------------------------------------- Tier 3 plugin/bridge
  {
    id: "archicad",
    providerFamily: "archicad",
    familyDisplayName: "Graphisoft",
    displayName: "Archicad",
    category: "BIM_CAD",
    connectionType: "PLUGIN_DESKTOP",
    status: "REQUIRES_PLUGIN",
    shortPurpose: "BIM authoring — connects via a desktop add-on, not cloud login.",
    description: "Archicad has no ordinary cloud OAuth login. The planned Quantara Archicad Connector is a signed desktop add-on: the user logs in to Quantara inside the connector, selects a Quantara project, and controls each export of selected element/property data.",
    supportedData: [],
    plannedData: ["Selected model elements", "Approved element/property export", "User-controlled synchronization"],
    recommendedOrder: 5,
    icon: "Building2",
    isIndependentIntegration: true,
  },
  {
    id: "tekla-structures",
    providerFamily: "tekla",
    familyDisplayName: "Trimble",
    displayName: "Tekla Structures",
    category: "STRUCTURAL_ENGINEERING",
    connectionType: "PLUGIN_DESKTOP",
    status: "COMING_SOON",
    shortPurpose: "Structural detailing and steel/concrete fabrication.",
    description: "Requires a desktop plugin — no cloud OAuth exists for this connection.",
    supportedData: [],
    plannedData: ["Model objects", "Assemblies", "Steel/concrete quantities", "Profiles", "Bolts", "Reinforcement", "Drawing links", "Fabrication data"],
    recommendedOrder: 14,
    icon: "Boxes",
    isIndependentIntegration: true,
  },
  {
    id: "sketchup",
    providerFamily: "sketchup",
    familyDisplayName: "Trimble",
    displayName: "SketchUp",
    category: "BIM_CAD",
    connectionType: "FILE_IMPORT",
    status: "FILE_IMPORT_ONLY",
    shortPurpose: "3D modeling — supported via file upload.",
    description: "SKP file upload and IFC export/import; a future extension connector may add live access.",
    supportedData: [],
    plannedData: ["SKP file upload", "IFC export/import"],
    recommendedOrder: 15,
    icon: "Shapes",
    isIndependentIntegration: true,
  },
  {
    id: "rhino-grasshopper",
    providerFamily: "rhino",
    familyDisplayName: "Robert McNeel & Associates",
    displayName: "Rhino + Grasshopper",
    category: "BIM_CAD",
    connectionType: "PLUGIN_DESKTOP",
    status: "COMING_SOON",
    shortPurpose: "Parametric 3D modeling and computational design.",
    description: "Requires a desktop plugin — no cloud OAuth exists for this connection.",
    supportedData: [],
    plannedData: ["Selected geometry", "Object metadata", "Parameter outputs", "Quantity schedules", "Grasshopper component connection"],
    recommendedOrder: 17,
    icon: "Shapes",
    isIndependentIntegration: true,
  },
  {
    id: "solidworks",
    providerFamily: "solidworks",
    familyDisplayName: "Dassault Systèmes",
    displayName: "SolidWorks",
    category: "BIM_CAD",
    connectionType: "FILE_IMPORT",
    status: "COMING_SOON",
    shortPurpose: "Mechanical CAD and manufacturing.",
    description: "Planned file-import support for assembly/BOM data.",
    supportedData: [],
    plannedData: ["Assembly/BOM data", "Component metadata", "Manufacturing quantities"],
    recommendedOrder: null,
    icon: "Cog",
    isIndependentIntegration: true,
  },
  {
    id: "vectorworks",
    providerFamily: "vectorworks",
    familyDisplayName: "Vectorworks",
    displayName: "Vectorworks",
    category: "BIM_CAD",
    connectionType: "FILE_IMPORT",
    status: "COMING_SOON",
    shortPurpose: "BIM and design software.",
    description: "Planned file-import support.",
    supportedData: [],
    plannedData: ["File import"],
    recommendedOrder: null,
    icon: "PenTool",
    isIndependentIntegration: true,
  },
  {
    id: "bentley-microstation",
    providerFamily: "bentley",
    familyDisplayName: "Bentley Systems",
    displayName: "MicroStation / OpenBuildings",
    category: "BIM_CAD",
    connectionType: "OAUTH_CLOUD",
    status: "COMING_SOON",
    shortPurpose: "Represented through the Bentley iTwin connection.",
    description: "Uses the same Bentley iTwin connection above — no duplicate connection logic.",
    supportedData: [],
    plannedData: ["Represented through Bentley iTwin"],
    recommendedOrder: null,
    icon: "Globe",
    isIndependentIntegration: true,
  },

  // ------------------------------------------------- Tier 4 structural engineering
  ...([
    ["etabs", "ETABS", "Computers and Structures, Inc. (CSI)", 18],
    ["safe", "SAFE", "Computers and Structures, Inc. (CSI)", 19],
    ["sap2000", "SAP2000", "Computers and Structures, Inc. (CSI)", 20],
    ["staad-pro", "STAAD.Pro", "Bentley Systems", null],
    ["robot-structural-analysis", "Robot Structural Analysis", "Autodesk", null],
    ["tekla-structural-designer", "Tekla Structural Designer", "Trimble", null],
  ] as const).map(([id, displayName, familyDisplayName, recommendedOrder]) => ({
    id,
    providerFamily: id,
    familyDisplayName,
    displayName,
    category: "STRUCTURAL_ENGINEERING" as const,
    connectionType: "FILE_IMPORT" as const,
    status: "COMING_SOON" as const,
    shortPurpose: "Structural analysis and design.",
    description: "No automatic model access exists yet — approved file import (CSV/XLSX schedules, PDF reports, IFC where available) is planned first.",
    supportedData: [],
    plannedData: ["Member schedules", "Section properties", "Material grades", "Loads", "Analysis results", "Reinforcement quantities", "Foundation schedules"],
    recommendedOrder,
    icon: "Building",
    isIndependentIntegration: true,
  })),

  // ---------------------------------------------- Tier 5 estimating/commercial
  ...([
    ["costx", "CostX", "RIB Software"],
    ["candy", "Candy", "RIB Software"],
    ["sage-estimating", "Sage Estimating", "Sage"],
    ["oracle-primavera-p6", "Oracle Primavera P6", "Oracle"],
    ["oracle-aconex", "Oracle Aconex", "Oracle"],
    ["autodesk-takeoff", "Autodesk Takeoff", "Autodesk"],
    ["planswift", "PlanSwift", "ConstructConnect"],
    ["rib-itwo", "RIB iTWO", "RIB Software"],
    ["sap", "SAP", "SAP"],
    ["oracle-erp", "Oracle ERP", "Oracle"],
    ["microsoft-dynamics-365", "Microsoft Dynamics 365", "Microsoft"],
    ["quickbooks", "QuickBooks", "Intuit"],
    ["xero", "Xero", "Xero"],
  ] as const).map(([id, displayName, familyDisplayName]) => ({
    id,
    providerFamily: id,
    familyDisplayName,
    displayName,
    category: "ESTIMATING_COST" as const,
    connectionType: "FILE_IMPORT" as const,
    status: "COMING_SOON" as const,
    shortPurpose: "Estimating and commercial data.",
    description: "Planned initial support: XLSX/CSV and approved BOQ export/import formats.",
    supportedData: [],
    plannedData: ["Cost codes", "Budget sync", "Supplier rates", "Purchase orders", "Project schedules", "Commercial reporting"],
    recommendedOrder: null,
    icon: "Calculator",
    isIndependentIntegration: true,
  })),
];

export function getProviderById(providerId: string): ProviderRegistryEntry | undefined {
  return PROVIDER_REGISTRY.find((p) => p.id === providerId);
}

export function getProvidersByFamily(providerFamily: string): ProviderRegistryEntry[] {
  return PROVIDER_REGISTRY.filter((p) => p.providerFamily === providerFamily);
}

export const INTEGRATION_CATEGORY_LABELS: Record<ProviderRegistryEntry["category"], string> = {
  BIM_CAD: "BIM and CAD",
  CONSTRUCTION_MANAGEMENT: "Construction Management",
  COMMON_DATA_ENVIRONMENTS: "Common Data Environments",
  DOCUMENTS_STORAGE: "Documents and Cloud Storage",
  ESTIMATING_COST: "Estimating and Cost",
  STRUCTURAL_ENGINEERING: "Structural Engineering",
  VISUALIZATION_RENDERING: "Visualization and Rendering",
};
