export const PUBLIC_INTEGRATION_IDS = [
  "autodesk",
  "revit",
  "autocad",
  "autodesk-construction-cloud",
  "autodesk-docs",
  "bim-360",
  "civil-3d",
  "navisworks",
  "3ds-max",
  "inventor",
  "fusion",
  "trimble-connect",
  "procore",
  "bentley-itwin",
  "bluebeam-studio",
  "microsoft-365",
  "google-drive",
  "dropbox",
  "box",
  "archicad",
  "tekla-structures",
  "sketchup",
  "rhino-grasshopper",
  "solidworks",
  "vectorworks",
  "bentley-microstation",
  "etabs",
  "safe",
  "sap2000",
  "staad-pro",
  "robot-structural-analysis",
  "tekla-structural-designer",
  "costx",
  "candy",
  "sage-estimating",
  "oracle-primavera-p6",
  "oracle-aconex",
  "autodesk-takeoff",
  "planswift",
  "rib-itwo",
  "sap",
  "oracle-erp",
  "microsoft-dynamics-365",
] as const;

export type PublicIntegrationId = (typeof PUBLIC_INTEGRATION_IDS)[number];

export const PUBLIC_INTEGRATION_PATHS = PUBLIC_INTEGRATION_IDS.map(
  (providerId) =>
    `/boq-integrations/${providerId}` as `/boq-integrations/${PublicIntegrationId}`,
);